### PR TITLE
Add Elder Guardian

### PR DESCRIPTION
**Pull request by Lunarmagpie**
Need to make the status effect work better

### CODE REVIEW

**Comment by alicetouhou** [comment]
Uh... I already enabled it?

**Comment by Lunarmagpie** [comment]
This ended up being a bit complex so I'm going to add more tests

**Comment by Lunarmagpie** [comment]
Mb fat fingered the close button

**Comment by Lunarmagpie** [comment]
This PR feels complete to me now! The tests are pretty awesome too!

**Pull request merged**
