### PR TITLE
Restore coin flip behavior

### PR DESCRIPTION
**Pull request by Screaper91**
- Fixes Sheep Stare and Aussie Ping being removed early by Thorns/Wolf
- Fixes opponent flip interactions with Bad Omen and Chorus Fruit
- Fixes Trap Hole interactions with Fire Charge, Piston and Bad Omen
- Fixes Trident damage and logging its coin flip

### CODE REVIEW

**Comment by Lunarmagpie** [comment]
Im not sure we want to change the status effects to be on the user of the attacks at the moment. Me and @Benji42 think they are more clear how they are set up now.
If you could make a PR with the bug fixes you found here that would be really helpful though!

**Comment by Screaper91** [comment]
I moved them back to the target of the attacks. They still use the user's attacking hermit to flip so everything works like before.

**Comment by Benji42** [comment]
Thank you! will merge

**Comment by Lunarmagpie** [comment]
Awesome work! Thank you!

**Pull request merged**
