### PR TITLE
Update AoTCG cards

### PR DESCRIPTION
**Pull request by Screaper91**
Updates AoTCG cards to ECS and fixes related issues.
### Fixes/changes for non-advent cards
- Applying **Curse of Binding** or **Fortune** twice in one turn with Gem's **Geminislay** no longer adds a redundant status effect
- Hypno's **Got 'Em** no longer discards the selected item card if it the attack was canceled by removing Crossbow
- Zedaph's **Sheep Stare** no longer reflects bonus AFK damage from Goatfather's **Anvil Drop** or Spooky Stress's **Wa'a**
- Boomer Bdubs's **Watch This** can no longer be canceled after flipping a coin
- Human Cleo's **Betrayed** can now force attacking an AFK when the opponent uses **Efficiency** or **Command Block** to power their attack
- Poe Poe Skizz's **Jumpscare** now requires you to decide if/where to move before attacking instead of after
- Worm Man's **Total Anonymity** no longer can turn face down the next card played if they end their turn immediately when mocked by **Puppetry/Role Play**

### CODE REVIEW

**Comment by Lunarmagpie** [comment]
Thanks for working on this! I know Benji wanted to get this done but he didn't have time.
If you can make a list to show progress that would be really helpful.

**Comment by Benji42** [comment]
I will update this later, but some balancing changes that need to be made:
Dropper: `Place a fletching table on the top of your opponent's deck.`
Grianch: `Flip a coin. If heads, you may attack an additional time. If tails, your opponent may attack twice next round.\nWhen this attack is used with Fortune, only the first coinflip will be affected.`
Glowstone: `View the top 3 cards of your opponent’s deck. Choose one to discard. The other 2 will be placed on the bottom of their deck in their original order.`

**Comment by Lunarmagpie** [comment]
I just merged master into your branch, you should be good to go with the new formatter!

**Comment by Screaper91** [comment]
Progress on pull request can be viewed at [https://github.com/users/Screaper91/projects/1](url).

**Comment by alicetouhou** [comment]
I looked at all your notes about changes on the spreadsheet and everything looks good, although I don't really know about what should happen for the grian interaction.

**Comment by alicetouhou** [comment]
I forgot to let you know about the buff I had planned for Lizzie, sorry. `Evict - Move your opponent's active Hermit and any attached cards to an open slot on their board, if one is available. If there's no open slots available, their active Hermit takes 60hp additional damage.` Although if you don't feel like changing it, I can myself soon.

**Comment by Screaper91** [comment]
>  `If there's no open slots available, their active Hermit takes 60hp additional damage.`

How should this interact with Slimeball preventing the attached row from moving? Deal extra damage or just not move it?

**Comment by alicetouhou** [comment]
Ohh, doesn't say anything about being able to be moved in that concept, so no extra damage, but actually it could be +40 damage if it's unable to be moved (by empty slots or slimeball). that might be more interesting. I don't know. well we have time to workshop it lol

**Comment by Lunarmagpie** [comment]
Could you move the advent of tcg tests into a different directory called `aotcg`. So it would be:
```
hermits/
effets/
aotcg/hermits/
aotcg/effects/
```

I think its important to prioritize regular hermits over AoTCG when tests fail so this will help make the distinction clearer.

**Comment by Lunarmagpie** [comment]
Thanks for moving the tests!

**Comment by Lunarmagpie** [comment]
Although Dungeon Master Tango works, the way that indexes are chosen means its possible for a deck slot to have a repeated order with an old one. This isn't an issue now but I don't want it to become one. It would be better if the existing ordering numbers were redistributed.

**Comment by alicetouhou** [comment]
Hey, is there anything particular you want help with?

**Comment by alicetouhou** [comment]
Furnace wild x2 - I like this, it allows for interesting interaction
Monkey farm rebalance - I rethought it and I think it's not needed. It's different enough from the other card with a similar ability, and nobody has given suggestions I like for it.
Lizzie - I would like to work on rebalancing this one, and I'll make a PR when I'm done
Ollie - don't worry about showing the creator, Lunar is working on a system for that so we'll do it after this is merged.

**Comment by alicetouhou** [comment]
Grianch Naughty + Geminislay > It's ok to let them use another effect after each attack, I think
Grianch Naughty + Wolf/thorns > These trigger on attack, so it's ok for them to trigger multiple times each turn
Grianch Naughty + Joepacity > If I correctly understand the issue, as long as you use joepacity once per turn it counts as consecutive, because the meaning we chose is consecutive terms.

**Comment by alicetouhou** [comment]
On your comments on trapdoor:
> Should this not redirect Hyperspace damage that attacks an adjacent empty row?

Yes
> Should this be unable to chain?

I think chaining is ok, it was pretty janky but also fun

**Comment by alicetouhou** [comment]
LGTM!

**Pull request merged**
