### PR TITLE
Improve Credits

### PR DESCRIPTION
**Pull request by Lunarmagpie**
Improves credits to fit more people on the screen

I added the gitlab logo since a contributer uses gitlab, but Its kinda small so if anyone wants to fix that it would be appreciated. I do not know enough about svgs to know what went wrong.

image

### CODE REVIEW

**Comment by alicetouhou** [comment]
You should include a picture in your description

**Comment by alicetouhou** [comment]
Please don't merge until I have a chance to review

**Comment by Screaper91** [comment]
Resized icon
I think this looks good enough to me if **alicetouhou** approves

**Comment by Lunarmagpie** [comment]
Thank you for fixing that @Screaper91 !

**Comment by alicetouhou** [comment]
I don't wanna bikeshed minor visual changes so looks good.

**Pull request merged**
