### PR TITLE
Play sound on game start for both players

### PR DESCRIPTION
**Pull request by Lunarmagpie**
Fixes a bug where only player one would hear a sound on game start

### CODE REVIEW

**Comment by Benji42** [comment]
double equals instead of ===

**Comment by Lunarmagpie** [comment]
> double equals instead of ===

fixed

**Comment by Benji42** [comment]
This might be part of the issue but I'm also pretty sure that there's other issues with this

**Comment by Benji42** [comment]
Ok nevermind, seems to work consistently now

**Comment by Benji42** [comment]
Jamm verified, I will merge this

**Pull request merged**
