### PR TITLE
Implement first 7 cards of AoTCG II

### PR DESCRIPTION
**Pull request by Screaper91**
Includes fixes for pre-existing advent bugs:
- Damage intercepted by Trapdoor is no longer re-doubled by Invisibility flipping tails
- Biffa's Museum always counts cards played to the board after using Chest or Flint & Steel
- Knocking out Berry Bush with multiple "attacks" at once no longer gives more than 2 Instant Health II potions

### CODE REVIEW

**Comment by alicetouhou** [comment]
Looks awesome! thank you

**Comment by Lunarmagpie** [comment]
Thanks for the work! I dont have many comments on this, I you and Benji can work on this without me.

**Comment by alicetouhou** [comment]
One small issue I noticed, it looks like frozen is missing from powdered snow bucket's sidebar descriptions

**Comment by alicetouhou** [comment]
Going to merge this anyway bc I can fix that, and I'm about to do a merge and don't want to make you deal with conflicts

**Pull request merged**
