### PR TITLE
Make it possible for status effect descriptions to be dynamic

### PR DESCRIPTION
**Pull request by Lunarmagpie**
It would be best to implement this for one status effect to prove the system is good before going ahead and merging 
This PR additionally sets up `InstancedValue` so it can be used with status effects.

### CODE REVIEW

**Comment by alicetouhou** [comment]
Ollie is the best candidate, but if course AoTCG isn't done yet. Maybe do skizz and show the total damage gained?

**Comment by Lunarmagpie** [comment]
I'm thinking the multi turn and single turn attack disabling effects could be merged together possibly.

**Comment by alicetouhou** [comment]
> I'm thinking the multi turn and single turn attack disabling effects could be merged together possibly.

How so? If it works go for it

**Comment by Lunarmagpie** [comment]
> > I'm thinking the multi turn and single turn attack disabling effects could be merged together possibly.
> 
> How so? If it works go for it

I think it actually won't work.

**Comment by alicetouhou** [comment]
Can we close this?

**Comment by Lunarmagpie** [comment]
> Can we close this?

No, I want to compare the methods than close this after we merge

**Pull request closed without merging**
