### PR TITLE
Validate starter decks

### PR DESCRIPTION
**Pull request by Lunarmagpie**

### CODE REVIEW

**Comment by alicetouhou** [comment]
I'm going to be annoying, if you're fixing this can you also make it so the decks just have the cards listed out instead of using code

**Comment by alicetouhou** [comment]
Also if you are working on this, you could expand the system to return a name and icon we can modify, would be great

**Comment by Lunarmagpie** [comment]
You're building a shed but I'll change it

**Comment by alicetouhou** [comment]
Looks good

**Pull request merged**
