### PR TITLE
Use Set Seed For Games

### PR DESCRIPTION
**Pull request by Lunarmagpie**
This is to help make it possible to run games on the client in the future. This is also helpful because this change makes tests 100% consistent as they are no longer reliant on RNG.

### CODE REVIEW

**Comment by Lunarmagpie** [comment]
> please make the database actually use the seed

Done

**Comment by alicetouhou** [comment]
LGTM

**Comment by alicetouhou** [comment]
Actually, how long is the seed? There may be an issue if it's over 15 characters

**Comment by Lunarmagpie** [comment]
> Actually, how long is the seed? There may be an issue if it's over 15 characters

Idk but I can make it 8

**Comment by Lunarmagpie** [comment]
Probably good to merge now

**Pull request merged**
