### PR TITLE
Create Docker Build CI

### PR DESCRIPTION
**Pull request by Lunarmagpie**
Adds CI to ensure that the docker image builds.
This will slow down CI a bit, but I think it worth running at least before merging in the main branch.

### CODE REVIEW

**Comment by Benji42** [comment]
What is this supposed to do?

**Comment by Benji42** [comment]
Yeah makes sense. I think this is a good addition. It's pretty bad we have docker issues that can delay releases after we say they're going to happen.

**Comment by Lunarmagpie** [comment]
We may not need this, the main change that has to be made is either:
- Do our test build CI with the `NODE_ENV=production`
- Or build the docker image without `NODE_ENV=production`

**Comment by Benji42** [comment]
yeah, sounds reasonable, LGTM

**Pull request merged**
