### PR TITLE
Fix consecutive Time Skip

### PR DESCRIPTION
**Pull request by Screaper91**
- Fixes mocking Time Skip after flipping heads
- Fixes actions being blocked/available at the wrong time due to knock-outs
- Fixes Role Play disabling all secondary attacks if opponent only has Armor Stand

### CODE REVIEW

**Comment by Screaper91** [comment]
I know this does not neaten the blocked actions system for #600 but it does add tests that will hopefully prevent bugs with the next refactor

**Comment by Lunarmagpie** [comment]
I just have a question about this interaction:
- Is the joehills time skip supposed to additionally prevent clock from being used, and vise versa?@alicetouhou

**Comment by Lunarmagpie** [comment]
> I know this does not neaten the blocked actions system for #600 but it does add tests that will hopefully prevent bugs with the next refactor

Np, it's fine to work with this current system until someone has time to investigate and redo it

**Review by Lunarmagpie — APPROVED** [review]
Everything that made me question "why is that like that" ended up being because of a limitation with blocked actions :(. LGTM. Definitely should investigate redoing those.

**Comment by alicetouhou** [comment]
> I just have a question about this interaction:
> 
>     * Is the joehills time skip supposed to additionally prevent clock from being used, and vise versa?@alicetouhou

correct

**Pull request merged**
